// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IHeaderFields {
  /** title */
  title?: string | undefined;
}

export interface IHeader extends Entry<IHeaderFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "header";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IJobFields {
  /** company name */
  companyName: string;

  /** job title */
  jobTitle: string;

  /** start date */
  startDate: string;

  /** end date */
  endDate?: string | undefined;

  /** description */
  description?: string | undefined;

  /** projects */
  projects?: IProject[] | undefined;

  /** city */
  city?: string | undefined;
}

export interface IJob extends Entry<IJobFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "job";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProjectFields {
  /** name */
  name?: string | undefined;

  /** description */
  description?: string | undefined;

  /** technologies */
  technologies?: string[] | undefined;

  /** tools */
  tools?: string[] | undefined;

  /** company */
  company?: string | undefined;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "project";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISchoolFields {
  /** name */
  name: string;

  /** description */
  description?: string | undefined;

  /** type */
  type: "highschool" | "university" | "academy" | "course" | "training";

  /** start date */
  startDate?: string | undefined;

  /** end date */
  endDate: string;

  /** location */
  location?: string | undefined;
}

export interface ISchool extends Entry<ISchoolFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "school";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISectionFields {
  /** name */
  name: string;

  /** title */
  title?: string | undefined;

  /** description */
  description?: Document | undefined;

  /** article */
  article?: (IJob | ISchool)[] | undefined;
}

export interface ISection extends Entry<ISectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "section";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISectionsFields {
  /** sections */
  section?: ISection[] | undefined;
}

export interface ISections extends Entry<ISectionsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sections";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "header"
  | "job"
  | "project"
  | "school"
  | "section"
  | "sections";

export type IEntry = IHeader | IJob | IProject | ISchool | ISection | ISections;

export type LOCALE_CODE = "pl";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "pl";
