import { ContentTypeCollection, EntryCollection } from "contentful";
import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { fetchDataTypes, fetchEntries } from "../contentful";
import styles from "../styles/Home.module.css";

interface Content {
  header: string;
  types: ContentTypeCollection;
  entries: EntryCollection<{ companyName: string }>;
}

const Home: NextPage<Content> = ({ header, types, entries }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>{header}</h1>
      </header>

      <main className={styles.main}>
        {entries.items.map((item, index) => (
          <section key={index}>
            <header>{item.fields.companyName}</header>
            <article></article>
          </section>
        ))}
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps<Content> = async () => {
  const types = await fetchDataTypes();
  const entries = await fetchEntries();

  return {
    props: {
      header: "SRUTUTURUTU",
      types,
      entries,
    },
  };
};

export default Home;
